import type { Page } from "./types.ts";

const amount: Page["slots"][number] = {
  id: "amount",
  label: "amount",
  required: false,
  values: [
    { id: "little", label: "a bit", aliases: ["a bit", "a little", "slightly", "notch"] },
    { id: "lot", label: "a lot", aliases: ["a lot", "way", "much"] },
  ],
};

const direction: Page["slots"][number] = {
  id: "direction",
  label: "direction",
  required: true,
  values: [
    { id: "up", label: "up", aliases: ["up", "louder", "increase", "raise", "higher", "brighter", "warmer"] },
    { id: "down", label: "down", aliases: ["down", "quieter", "decrease", "lower", "dim", "colder", "cooler", "darker"] },
  ],
};

export const PAGES: Page[] = [
  {
    id: "wm.focus",
    module: "wm",
    kind: "act",
    title: "Focus a window",
    summary: "Switch to a live client matched by class, title, or alias.",
    aliases: ["switch to", "focus", "go to", "show me", "bring up"],
    slots: [
      {
        id: "target",
        label: "window",
        required: true,
        values: [
          { id: "jellyfin", label: "Jellyfin", aliases: ["jellyfin", "the tv app", "movies", "the show"] },
          { id: "grokbot", label: "Grok Bot", aliases: ["grokbot", "grok bot", "the bot"] },
          { id: "firefox", label: "Firefox", aliases: ["firefox", "browser", "the other browser"] },
          { id: "kitty", label: "Terminal", aliases: ["terminal", "kitty", "shell"] },
          { id: "code", label: "Editor", aliases: ["editor", "code", "vscode"] },
          { id: "thunderbird", label: "Mail app", aliases: ["thunderbird", "mail app"] },
        ],
      },
    ],
    when: "A client whose class/title matches target is mapped.",
    policy: "household",
    walk: "hyprctl dispatch focuswindow address:<addr>",
    examples: ["switch to jellyfin", "focus the terminal", "go to grokbot"],
    refuse: ["click the second tab", "the one on the left of the red one"],
  },
  {
    id: "wm.fullscreen",
    module: "wm",
    kind: "act",
    title: "Fullscreen",
    summary: "Fullscreen the focused or named client.",
    aliases: ["fullscreen", "full screen", "make this bigger", "maximise", "maximize"],
    slots: [
      {
        id: "target",
        label: "window",
        required: false,
        values: [
          { id: "active", label: "this", aliases: ["this", "that"] },
          { id: "jellyfin", label: "Jellyfin", aliases: ["jellyfin"] },
          { id: "grokbot", label: "Grok Bot", aliases: ["grokbot", "grok bot"] },
        ],
      },
    ],
    when: "Target client exists and is not already fullscreen.",
    policy: "household",
    walk: "focus if needed, then hyprctl dispatch fullscreen 1",
    examples: ["fullscreen this", "switch to jellyfin and fullscreen"],
    refuse: ["make it look nicer"],
  },
  {
    id: "wm.workspace",
    module: "wm",
    kind: "act",
    title: "Switch workspace",
    summary: "Named or numbered workspace on the current monitor.",
    aliases: ["workspace", "desk", "go to workspace"],
    slots: [
      {
        id: "ws",
        label: "workspace",
        required: true,
        values: [
          { id: "1", label: "one", aliases: ["one", "1", "first"] },
          { id: "2", label: "two", aliases: ["two", "2"] },
          { id: "3", label: "three", aliases: ["three", "3"] },
          { id: "4", label: "four", aliases: ["four", "4"] },
          { id: "special", label: "scratch", aliases: ["scratch", "special", "hidden"] },
        ],
      },
    ],
    when: "Workspace id is in the live set or is creatable.",
    policy: "household",
    walk: "hyprctl dispatch workspace <ws>",
    examples: ["workspace three", "go to two"],
    refuse: [],
  },
  {
    id: "wm.move_ws",
    module: "wm",
    kind: "act",
    title: "Move window to workspace",
    summary: "Move focused (or named) client silently, then optionally follow.",
    aliases: ["put this on", "move this to", "send to workspace"],
    slots: [
      {
        id: "ws",
        label: "workspace",
        required: true,
        values: [
          { id: "1", label: "one", aliases: ["one", "1"] },
          { id: "2", label: "two", aliases: ["two", "2"] },
          { id: "3", label: "three", aliases: ["three", "3"] },
        ],
      },
    ],
    when: "A focused client exists.",
    policy: "household",
    walk: "hyprctl dispatch movetoworkspace <ws>",
    examples: ["put this on three"],
    refuse: [],
  },
  {
    id: "wm.close",
    module: "wm",
    kind: "act",
    title: "Close window",
    summary: "Close focused or named client. Named 'other browser' uses kill_other logic.",
    aliases: ["close", "kill", "quit this window"],
    slots: [
      {
        id: "target",
        label: "window",
        required: false,
        values: [
          { id: "active", label: "this", aliases: ["this"] },
          { id: "firefox", label: "browser", aliases: ["browser", "firefox", "the other browser"] },
        ],
      },
    ],
    when: "Target client exists.",
    policy: "confirm",
    walk: "hyprctl dispatch killactive or focus then kill",
    examples: ["close this", "kill the other browser"],
    refuse: ["close everything"],
  },
  {
    id: "wm.float",
    module: "wm",
    kind: "act",
    title: "Toggle floating",
    summary: "Float or tile the focused window.",
    aliases: ["float", "unfloat", "tile this"],
    slots: [],
    when: "A focused client exists.",
    policy: "household",
    walk: "hyprctl dispatch togglefloating",
    examples: ["float this"],
    refuse: [],
  },
  {
    id: "wm.monitor",
    module: "wm",
    kind: "act",
    title: "Other monitor",
    summary: "Move focus to the next monitor.",
    aliases: ["other monitor", "other screen", "that display"],
    slots: [],
    when: "More than one monitor is connected.",
    policy: "household",
    walk: "hyprctl dispatch focusmonitor +1",
    examples: ["other monitor"],
    refuse: [],
  },
  {
    id: "wm.split_beside",
    module: "wm",
    kind: "act",
    title: "Open beside",
    summary: "Launch an allowlisted app in a split next to the focused window.",
    aliases: ["beside", "next to", "split with"],
    slots: [
      {
        id: "app",
        label: "app",
        required: true,
        values: [
          { id: "kitty", label: "terminal", aliases: ["terminal", "kitty"] },
          { id: "firefox", label: "browser", aliases: ["browser", "firefox"] },
        ],
      },
    ],
    when: "App is allowlisted.",
    policy: "household",
    walk: "hyprctl dispatch exec [tile] <bin>",
    examples: ["open a terminal beside the editor"],
    refuse: [],
  },
  {
    id: "wm.ask_focused",
    module: "wm",
    kind: "ask",
    title: "What is focused",
    summary: "Return class/title/workspace of the active window.",
    aliases: ["what's focused", "what is focused", "what am i looking at"],
    slots: [],
    when: "Always when Hyprland is up.",
    policy: "household",
    askShape: "{ class, title, workspace, fullscreen }",
    examples: ["what's focused"],
    refuse: [],
  },
  {
    id: "wm.ask_where",
    module: "wm",
    kind: "ask",
    title: "Where is an app",
    summary: "Workspace of a named class.",
    aliases: ["which workspace", "where is"],
    slots: [
      {
        id: "target",
        label: "window",
        required: true,
        values: [
          { id: "firefox", label: "Firefox", aliases: ["firefox", "browser"] },
          { id: "jellyfin", label: "Jellyfin", aliases: ["jellyfin"] },
          { id: "grokbot", label: "Grok Bot", aliases: ["grokbot", "grok bot"] },
        ],
      },
    ],
    when: "Target client exists.",
    policy: "household",
    askShape: "{ workspace, address, focused }",
    examples: ["which workspace is firefox on"],
    refuse: [],
  },
  {
    id: "audio.bump",
    module: "audio",
    kind: "act",
    title: "Nudge volume",
    summary: "Change default sink by a notch. 'A bit' is 5%, never a model-invented percent.",
    aliases: ["volume", "louder", "quieter", "turn it", "turn the volume"],
    slots: [direction, amount],
    when: "Default sink exists. Up is live only if volume < 1.0.",
    policy: "household",
    walk: "wpctl set-volume -l 1.0 @DEFAULT_SINK@ 5%+ | 5%-",
    examples: ["increase the volume a bit", "turn it down", "quieter"],
    refuse: ["set volume to 37 percent"],
  },
  {
    id: "audio.mute",
    module: "audio",
    kind: "act",
    title: "Mute sink",
    summary: "Mute the default output.",
    aliases: ["mute", "silence", "shut up"],
    slots: [],
    when: "Sink exists and is not muted.",
    policy: "household",
    walk: "wpctl set-mute @DEFAULT_SINK@ 1",
    examples: ["mute"],
    refuse: [],
  },
  {
    id: "audio.unmute",
    module: "audio",
    kind: "act",
    title: "Unmute sink",
    summary: "Unmute the default output.",
    aliases: ["unmute", "sound on"],
    slots: [],
    when: "Sink is muted.",
    policy: "household",
    walk: "wpctl set-mute @DEFAULT_SINK@ 0",
    examples: ["unmute"],
    refuse: [],
  },
  {
    id: "audio.headphones",
    module: "audio",
    kind: "act",
    title: "Headphones",
    summary: "Set default sink to the headphones node if present.",
    aliases: ["headphones", "headset"],
    slots: [],
    when: "A headphones sink is in wpctl status.",
    policy: "household",
    walk: "wpctl set-default <headphones-id>",
    examples: ["headphones"],
    refuse: [],
  },
  {
    id: "audio.speakers",
    module: "audio",
    kind: "act",
    title: "Speakers / TV",
    summary: "Set default sink to speakers or TV.",
    aliases: ["speakers", "tv speakers", "the tv"],
    slots: [],
    when: "Named sink exists.",
    policy: "household",
    walk: "wpctl set-default <speakers-id>",
    examples: ["tv speakers"],
    refuse: [],
  },
  {
    id: "audio.ask_level",
    module: "audio",
    kind: "ask",
    title: "How loud",
    summary: "Return current volume and mute.",
    aliases: ["how loud", "what's the volume", "how loud am i"],
    slots: [],
    when: "Sink exists.",
    policy: "household",
    askShape: "{ volume, muted, sink }",
    examples: ["how loud am i", "what's the volume"],
    refuse: [],
  },
  {
    id: "launch.app",
    module: "launch",
    kind: "act",
    title: "Open allowlisted app",
    summary: "Exec if not running; focus if it is. Allowlist only.",
    aliases: ["open", "open up", "launch", "start"],
    slots: [
      {
        id: "app",
        label: "app",
        required: true,
        values: [
          { id: "grokbot", label: "Grok Bot", aliases: ["grokbot", "grok bot", "the bot"] },
          { id: "firefox", label: "Firefox", aliases: ["firefox", "browser"] },
          { id: "kitty", label: "Terminal", aliases: ["terminal", "kitty"] },
          { id: "jellyfin", label: "Jellyfin", aliases: ["jellyfin", "the tv app"] },
          { id: "thunderbird", label: "Thunderbird", aliases: ["thunderbird", "mail"] },
          { id: "files", label: "Files", aliases: ["files", "downloads"] },
        ],
      },
    ],
    when: "App is on the allowlist.",
    policy: "household",
    walk: "if running: wm.focus; else hyprctl dispatch exec <bin>",
    examples: ["open up grokbot", "launch firefox"],
    refuse: ["open a random website", "run this curl"],
  },
  {
    id: "launch.ask_running",
    module: "launch",
    kind: "ask",
    title: "Is it open",
    summary: "Whether an allowlisted app already has a client.",
    aliases: ["is it open", "already open", "is grokbot already open"],
    slots: [
      {
        id: "app",
        label: "app",
        required: true,
        values: [
          { id: "grokbot", label: "Grok Bot", aliases: ["grokbot", "grok bot"] },
          { id: "jellyfin", label: "Jellyfin", aliases: ["jellyfin"] },
          { id: "firefox", label: "Firefox", aliases: ["firefox"] },
        ],
      },
    ],
    when: "Always.",
    policy: "household",
    askShape: "{ running, workspace }",
    examples: ["is grokbot already open"],
    refuse: [],
  },
  {
    id: "mail.from",
    module: "mail",
    kind: "ask",
    title: "Mail from someone",
    summary: "Count and latest subjects from a contact. Not a summary essay.",
    aliases: ["email from", "emails from", "mail from", "did dave", "have i received", "anything from"],
    slots: [
      {
        id: "who",
        label: "person",
        required: true,
        values: [
          { id: "dave", label: "Dave", aliases: ["dave"] },
          { id: "school", label: "school", aliases: ["school", "the school"] },
          { id: "anyone", label: "anyone", aliases: ["anyone", "anybody"] },
        ],
      },
    ],
    when: "Mail module online and speaker owns the account. Hidden if guest occupants.",
    policy: "private",
    askShape: "{ count, latest_at, subjects[≤3] }",
    examples: ["have I received any emails from Dave", "anything from school"],
    refuse: ["read me the whole thread", "email dave that i'll be late"],
  },
  {
    id: "mail.unread",
    module: "mail",
    kind: "ask",
    title: "Unread count",
    summary: "How many unread in the inbox.",
    aliases: ["unread", "any mail", "anything unread", "new mail"],
    slots: [],
    when: "Mail online, private session.",
    policy: "private",
    askShape: "{ unread }",
    examples: ["anything unread", "don't read it out — just yes or no"],
    refuse: [],
  },
  {
    id: "mail.open_last",
    module: "mail",
    kind: "act",
    title: "Open last from contact",
    summary: "Open the latest message from a contact in the mail app. Confirm if others present.",
    aliases: ["open dave's last", "open that mail"],
    slots: [
      {
        id: "who",
        label: "person",
        required: true,
        values: [
          { id: "dave", label: "Dave", aliases: ["dave"] },
        ],
      },
    ],
    when: "At least one message from contact. Confirm page if occupants > 1.",
    policy: "confirm",
    walk: "launch thunderbird + open message id",
    examples: ["open Dave's last mail"],
    refuse: ["send a reply"],
  },
  {
    id: "mail.flag",
    module: "mail",
    kind: "act",
    title: "Flag for later",
    summary: "Pin/flag the latest matching message. Does not send.",
    aliases: ["call it later", "flag that", "pin that mail"],
    slots: [],
    when: "A current mail context exists.",
    policy: "private",
    walk: "notmuch tag +flag",
    examples: ["call it later"],
    refuse: [],
  },
  {
    id: "media.play_pause",
    module: "media",
    kind: "act",
    title: "Play / pause",
    summary: "Toggle the active player.",
    aliases: ["pause", "play", "resume", "put the show back on"],
    slots: [],
    when: "A player is available.",
    policy: "household",
    walk: "playerctl play-pause",
    pose: "peace",
    examples: ["pause", "put the show back on"],
    refuse: [],
  },
  {
    id: "media.next",
    module: "media",
    kind: "act",
    title: "Skip",
    summary: "Next track / chapter.",
    aliases: ["skip", "next", "next one"],
    slots: [],
    when: "Player is playing or paused.",
    policy: "household",
    walk: "playerctl next",
    examples: ["skip"],
    refuse: [],
  },
  {
    id: "media.prev",
    module: "media",
    kind: "act",
    title: "Previous",
    summary: "Previous track.",
    aliases: ["previous", "go back", "last one"],
    slots: [],
    when: "Player exists.",
    policy: "household",
    walk: "playerctl previous",
    examples: ["go back"],
    refuse: [],
  },
  {
    id: "media.ask_now",
    module: "media",
    kind: "ask",
    title: "Now playing",
    summary: "Title / artist / player name.",
    aliases: ["what am i watching", "what's playing", "now playing"],
    slots: [],
    when: "Player exists.",
    policy: "household",
    askShape: "{ title, artist, player, playing }",
    examples: ["what am I watching"],
    refuse: [],
  },
  {
    id: "bucky.hide",
    module: "bucky",
    kind: "act",
    title: "Hide buddy",
    summary: "Dismiss the overlay.",
    aliases: ["hide the buddy", "i'm done", "go away"],
    slots: [],
    when: "BuckyBoi is visible.",
    policy: "household",
    walk: "buckyboi --hide via sock",
    pose: "fist",
    examples: ["I'm done — hide the buddy"],
    refuse: [],
  },
  {
    id: "bucky.listen",
    module: "bucky",
    kind: "act",
    title: "Start listen",
    summary: "Enter Listening if the gate allows. Usually a BuckyBoi-local pose.",
    aliases: ["listen", "i'm talking"],
    slots: [],
    when: "Gate passes for who.",
    policy: "household",
    walk: "buckyboi listen",
    pose: "palm",
    examples: [],
    refuse: [],
  },
  {
    id: "bucky.mic_mute",
    module: "bucky",
    kind: "act",
    title: "Mute mic path",
    summary: "Local ASR mute, not the PipeWire sink.",
    aliases: ["mute the mic", "stop listening"],
    slots: [],
    when: "Mic path is open.",
    policy: "household",
    walk: "buckyboi mute-asr",
    examples: ["unmute the mic", "mute the mic"],
    refuse: [],
  },
  {
    id: "bucky.ask_who",
    module: "bucky",
    kind: "ask",
    title: "Who is here",
    summary: "Auth chip + occupants as the house currently believes.",
    aliases: ["who does the house think", "who is here", "that's me"],
    slots: [],
    when: "Always.",
    policy: "household",
    askShape: "{ chip, occupants, gate }",
    examples: ["who does the house think is here"],
    refuse: [],
  },
  {
    id: "scene.apply",
    module: "scene",
    kind: "act",
    title: "Apply named scene",
    summary: "GlassSpear recipe. Never 'make it cozy' — only authored ids.",
    aliases: ["scene", "kitchen cook", "living room watch", "bedroom night", "same as last night"],
    slots: [
      {
        id: "scene",
        label: "scene",
        required: true,
        values: [
          { id: "kitchen-cook", label: "Kitchen cook", aliases: ["kitchen cook", "cook", "recipe"] },
          { id: "living-watch", label: "Living watch", aliases: ["living room watch", "watch", "movie time"] },
          { id: "bedside-night", label: "Bedside night", aliases: ["bedroom night", "bedside night", "same as last night"] },
          { id: "house-idle", label: "House idle", aliases: ["that's enough screens", "kitchen off", "screens off"] },
          { id: "quiet-hours", label: "Quiet hours", aliases: ["quiet hours"] },
        ],
      },
    ],
    when: "Scene id is in the library and policy allows it for occupants.",
    policy: "household",
    walk: "Surface API apply_scene",
    examples: ["kitchen cook", "living room watch", "bedroom night"],
    refuse: ["make it look nicer", "whatever i usually do"],
  },
  {
    id: "scene.lock_private",
    module: "scene",
    kind: "act",
    title: "Lock private panes",
    summary: "Tear down personal pages on a shared surface.",
    aliases: ["lock this", "someone's coming", "shared only"],
    slots: [],
    when: "Surface has private panes or guests arriving.",
    policy: "owner",
    walk: "Surface API lock_private",
    examples: ["lock this — someone's coming in", "shared only"],
    refuse: [],
  },
  {
    id: "scene.guest",
    module: "scene",
    kind: "act",
    title: "Guest mode",
    summary: "Force shared_only and hide private pages.",
    aliases: ["guest mode", "we have a guest"],
    slots: [],
    when: "Always.",
    policy: "owner",
    walk: "session.privacy_state = shared_only",
    examples: ["guest mode"],
    refuse: [],
  },
  {
    id: "scene.ask_active",
    module: "scene",
    kind: "ask",
    title: "Active scene",
    summary: "What recipe a room is on.",
    aliases: ["what scene", "is the living room on", "kitchen off"],
    slots: [
      {
        id: "room",
        label: "room",
        required: false,
        values: [
          { id: "living", label: "living", aliases: ["living", "living room"] },
          { id: "kitchen", label: "kitchen", aliases: ["kitchen"] },
          { id: "bedroom", label: "bedroom", aliases: ["bedroom", "bedside"] },
        ],
      },
    ],
    when: "Controller has a session for that surface.",
    policy: "household",
    askShape: "{ surface, scene, occupants }",
    examples: ["what scene is the living room on", "is the living room on"],
    refuse: [],
  },
  {
    id: "scene.handoff",
    module: "scene",
    kind: "act",
    title: "Handoff media",
    summary: "Move now-playing to another surface. Later GlassSpear epic; page exists so it can be tested as denied until wired.",
    aliases: ["put it on the tv", "jump to the living room", "put jellyfin on the tv"],
    slots: [
      {
        id: "surface",
        label: "surface",
        required: true,
        values: [
          { id: "living", label: "living room", aliases: ["living room", "tv"] },
          { id: "kitchen", label: "kitchen", aliases: ["kitchen"] },
        ],
      },
    ],
    when: "Handoff driver is enabled and target surface is online.",
    policy: "household",
    walk: "GlassSpear handoff protocol",
    examples: ["put Jellyfin on the TV", "jump to the living room"],
    refuse: [],
  },
  {
    id: "notify.read_last",
    module: "notify",
    kind: "ask",
    title: "Last notification",
    summary: "App + summary of the latest notification.",
    aliases: ["last notification", "what was that ping"],
    slots: [],
    when: "History is non-empty.",
    policy: "private",
    askShape: "{ app, summary, age_sec }",
    examples: ["what was that ping"],
    refuse: [],
  },
  {
    id: "lights.bump",
    module: "lights",
    kind: "act",
    title: "Nudge lights",
    summary: "Room group brightness by a notch.",
    aliases: ["lights", "dim", "brighter"],
    slots: [direction, amount],
    when: "Room light group exists.",
    policy: "household",
    walk: "HA light.turn_on brightness_step",
    examples: ["lights down a notch", "brighter"],
    refuse: ["set the hue to 240"],
  },
  {
    id: "lights.off",
    module: "lights",
    kind: "act",
    title: "Lights off",
    summary: "Named room group off.",
    aliases: ["lights off", "kitchen off"],
    slots: [
      {
        id: "room",
        label: "room",
        required: false,
        values: [
          { id: "here", label: "here", aliases: ["here"] },
          { id: "kitchen", label: "kitchen", aliases: ["kitchen"] },
          { id: "living", label: "living", aliases: ["living", "living room"] },
        ],
      },
    ],
    when: "Group exists.",
    policy: "household",
    walk: "HA light.turn_off",
    examples: ["kitchen off"],
    refuse: [],
  },
  {
    id: "timer.start",
    module: "timer",
    kind: "act",
    title: "Start timer",
    summary: "Authored durations only.",
    aliases: ["timer", "start a timer"],
    slots: [
      {
        id: "mins",
        label: "minutes",
        required: true,
        values: [
          { id: "5", label: "five", aliases: ["five", "5"] },
          { id: "10", label: "ten", aliases: ["ten", "10"] },
          { id: "15", label: "fifteen", aliases: ["fifteen", "15"] },
          { id: "20", label: "twenty", aliases: ["twenty", "20"] },
        ],
      },
    ],
    when: "No timer, or replace is allowed.",
    policy: "household",
    walk: "timer daemon start",
    examples: ["timer five minutes", "start the timer"],
    refuse: ["wake me at seven"],
  },
  {
    id: "timer.add",
    module: "timer",
    kind: "act",
    title: "Add time",
    summary: "Add five minutes to a running timer.",
    aliases: ["add five minutes", "more time"],
    slots: [],
    when: "A timer is running.",
    policy: "household",
    walk: "timer daemon add 300",
    examples: ["add five minutes"],
    refuse: [],
  },
  {
    id: "timer.ask",
    module: "timer",
    kind: "ask",
    title: "Time left",
    summary: "Seconds remaining.",
    aliases: ["how long on the oven", "how long left", "timer left"],
    slots: [],
    when: "Timer running.",
    policy: "household",
    askShape: "{ remaining_sec }",
    examples: ["how long on the oven"],
    refuse: [],
  },
  {
    id: "timer.cancel",
    module: "timer",
    kind: "act",
    title: "Cancel timer",
    summary: "Stop the running timer.",
    aliases: ["cancel the timer", "stop the timer"],
    slots: [],
    when: "Timer running.",
    policy: "household",
    walk: "timer daemon cancel",
    examples: ["cancel the timer"],
    refuse: [],
  },
  {
    id: "calendar.ask_next",
    module: "calendar",
    kind: "ask",
    title: "What's next",
    summary: "Next calendar event for the speaker. Hidden with guests.",
    aliases: ["what's next on my calendar", "what's on my calendar", "next appointment", "what's coming up"],
    slots: [],
    when: "Calendar online and speaker owns the account. Hidden if guest occupants.",
    policy: "private",
    askShape: "{ title, in_min }",
    examples: ["what's next on my calendar", "what's coming up"],
    refuse: ["schedule a meeting with Dave", "invite the school"],
  },
  {
    id: "calendar.ask_today",
    module: "calendar",
    kind: "ask",
    title: "Today's count",
    summary: "How many remaining events today. Not a readout of every title.",
    aliases: ["how busy am i", "anything else today", "how many meetings"],
    slots: [],
    when: "Calendar online, private session.",
    policy: "private",
    askShape: "{ remaining }",
    examples: ["how busy am I today"],
    refuse: [],
  },
  {
    id: "display.bump",
    module: "display",
    kind: "act",
    title: "Nudge screen brightness",
    summary: "Panel brightness by a notch. Separate from room lights.",
    aliases: ["dim the screen", "screen brighter", "display brightness", "screen darker"],
    slots: [direction, amount],
    when: "A panel is present.",
    policy: "household",
    walk: "brightnessctl set 5%+ | 5%-",
    examples: ["dim the screen", "screen brighter"],
    refuse: ["set brightness to 37 percent"],
  },
  {
    id: "display.night",
    module: "display",
    kind: "act",
    title: "Night light",
    summary: "Toggle the authored night-light preset. Not a free kelvin.",
    aliases: ["night light", "warm the screen", "blue light"],
    slots: [],
    when: "Night-light preset exists.",
    policy: "household",
    walk: "hyprctl hyprsunset temperature 3500 or authored toggle",
    examples: ["night light"],
    refuse: ["set colour temperature to 2400"],
  },
  {
    id: "climate.bump",
    module: "climate",
    kind: "act",
    title: "Nudge climate",
    summary: "Room climate group by one degree. Never a model-invented setpoint.",
    aliases: ["warmer", "colder", "turn the air", "a bit warmer", "a bit cooler"],
    slots: [direction, amount],
    when: "Climate entity exists in this room.",
    policy: "household",
    walk: "HA climate.set_temperature temperature_step ±1",
    examples: ["a bit warmer", "colder"],
    refuse: ["set the thermostat to 22.7"],
  },
  {
    id: "climate.off",
    module: "climate",
    kind: "act",
    title: "Climate off",
    summary: "Turn the room climate group off.",
    aliases: ["air off", "ac off", "climate off", "heater off"],
    slots: [],
    when: "Climate entity exists and is on.",
    policy: "household",
    walk: "HA climate.turn_off",
    examples: ["air off"],
    refuse: [],
  },
  {
    id: "capture.screenshot",
    module: "capture",
    kind: "act",
    title: "Screenshot",
    summary: "Capture the focused output to Pictures. Confirm if guest present.",
    aliases: ["screenshot", "snap the screen", "grab the screen"],
    slots: [],
    when: "An output is focused.",
    policy: "confirm",
    walk: "grim -o <output> ~/Pictures/vikett-<ts>.png",
    examples: ["screenshot", "snap the screen"],
    refuse: ["email that screenshot to Dave"],
  },
  {
    id: "weather.ask",
    module: "weather",
    kind: "ask",
    title: "Weather here",
    summary: "Short condition for this location. Not packing advice.",
    aliases: ["what's the weather", "is it going to rain", "weather outside"],
    slots: [],
    when: "Weather snap is non-null.",
    policy: "household",
    askShape: "{ condition }",
    examples: ["what's the weather", "is it going to rain"],
    refuse: ["should I take a jacket"],
  },
];
